spring.application.name=locadoradecarros

spring.datasource.url=jdbc:postgresql://localhost:5432/locadoradecarros
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update